<tsd:PluginWindowBase x:Class="MB_CutObject.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
        xmlns:local="clr-namespace:MB_CutObject.Views"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog" 
                      xmlns:viewmodels="clr-namespace:MB_CutObject.ViewModels" d:DataContext="{d:DesignInstance Type=viewmodels:MainWindowViewModel}"
                      mc:Ignorable="d"
        Title="Вырезы" Height="600" Width="800" ResizeMode="NoResize" WindowStartupLocation="CenterOwner" Background="#FFF0F0F0" >
    <Window.Resources>
        <Style TargetType="ItemsControl">
            <Setter Property="Padding" Value="2"/>
        </Style>
        <Style TargetType="Button">
            <Setter Property="HorizontalContentAlignment" Value="Center"/>
            <Setter Property="VerticalContentAlignment" Value="Center"/>
        </Style>
        <Style TargetType="TextBox">
            <Setter Property="VerticalContentAlignment" Value="Center"/>
            <Setter Property="VerticalAlignment" Value="Center"/>
            <Setter Property="Padding" Value="5"/>
        </Style>
        <Style TargetType="Label">
            <Setter Property="VerticalAlignment" Value="Center"/>
        </Style>
        <Style TargetType="UIControls:WpfFilterCheckBox">
            <Setter Property="VerticalAlignment" Value="Center"/>
            <Setter Property="HorizontalAlignment" Value="Center"/>
            <Setter Property="Padding" Value="5"/>
        </Style>
        <Style TargetType="StackPanel">
            <Setter Property="Margin" Value="0,5"/>
        </Style>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition/>
            <RowDefinition Height="50"/>
        </Grid.RowDefinitions>
        <Grid Grid.Row="1">
            <StackPanel Orientation="Horizontal">
                <StackPanel Orientation="Vertical">
                    <StackPanel Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox AttributeName="typeCut"/>
                        <ComboBox x:Name="cb_typeCut" SelectedIndex="{Binding TypeCut}" ScrollViewer.HorizontalScrollBarVisibility="Hidden">
                            <Canvas Margin="5"  Width="125" Height="150">
                                <Path Data="M 20,40 l30,0 a 30,30 0 0 1 30,30 l 0,50 40,0 0,-120 -100,0 Z" StrokeThickness="1" Stroke="Black" Fill="#FFFFCF63"/>
                                <Path Data="M 3,40 l17,0" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 3,120 l97,0" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 13,40 l0,80" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 20,40 l0,100" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 80,120 l0,20" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 20,135 l60,0" StrokeThickness="0.5" Stroke="Black"/>
                                <Path Data="M 8,115 l5,5 5,-5 Z" StrokeThickness="0.5" Stroke="Black" Fill="Black"/>
                                <Path Data="M 8,45 l5,-5 5,5 Z" StrokeThickness="0.5" Stroke="Black" Fill="Black"/>
                                <Path Data="M 20,135 l5,-5 0,10 Z" StrokeThickness="0.5" Stroke="Black" Fill="Black"/>
                                <Path Data="M 80,135 l-5,-5 0,10 Z" StrokeThickness="0.5" Stroke="Black" Fill="Black"/>
                                <TextBlock Text="H" Margin="0,72" VerticalAlignment="Center"/>
                                <TextBlock Text="L" Canvas.Left="45" Canvas.Top="120"/>
                            </Canvas>
                            <Canvas Margin="5"  Width="125" Height="150">

                            </Canvas>
                        </ComboBox>
                    </StackPanel>
                </StackPanel>
                <StackPanel Orientation="Vertical">
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_Height" Content="H" Width="25"/>
                        <UIControls:WpfFilterCheckBox AttributeName="height"/>
                        <TextBox x:Name="tb_Height" Text="{Binding Height, Mode=TwoWay}" Height="25" Width="100"/>
                    </StackPanel>
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_Width" Content="L" Width="25"/>
                        <UIControls:WpfFilterCheckBox AttributeName="width"/>
                        <TextBox x:Name="tb_Width" Text="{Binding Width, Mode=TwoWay}" Height="25" Width="100"/>
                    </StackPanel>
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_Radius" Content="R" Width="25"/>
                        <UIControls:WpfFilterCheckBox AttributeName="radius"/>
                        <TextBox x:Name="tb_Radius" Text="{Binding Radius, Mode=TwoWay}" Height="25" Width="100"/>
                    </StackPanel>
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_offsetH" Content="H1" Width="25"/>
                        <UIControls:WpfFilterCheckBox AttributeName="offsetH"/>
                        <TextBox x:Name="tb_offsetH" Text="{Binding OffsetH, Mode=TwoWay}" Height="25" Width="100"/>
                    </StackPanel>
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_offsetL" Content="L1" Width="25"/>
                        <UIControls:WpfFilterCheckBox AttributeName="offsetL"/>
                        <TextBox x:Name="tb_offsetL" Text="{Binding OffsetL, Mode=TwoWay}" Height="25" Width="100"/>
                    </StackPanel>
                    <StackPanel Orientation="Horizontal">
                        <Label x:Name="l_mirror" Content="Зеркально отразить"/>
                        <UIControls:WpfFilterCheckBox AttributeName="mirror"/>
                        <ComboBox x:Name="cb_mirror" SelectedIndex="{Binding Mirror}" Width="120">
                            <TextBlock Text="Нет"/>
                            <TextBlock Text="Вертикально"/>
                            <TextBlock Text="Горизонтально"/>
                        </ComboBox>
                    </StackPanel>
                </StackPanel>
            </StackPanel>
        </Grid>
        <UIControls:WpfSaveLoad Grid.Row="0" HorizontalAlignment="Stretch" VerticalAlignment="Top" />
        <UIControls:WpfOkApplyModifyGetOnOffCancel Grid.Row="2" HorizontalAlignment="Stretch" VerticalAlignment="Bottom" ApplyClicked="WPFOkApplyModifyGetOnOffCancel_ApplyClicked" CancelClicked="WPFOkApplyModifyGetOnOffCancel_CancelClicked" GetClicked="WPFOkApplyModifyGetOnOffCancel_GetClicked" OkClicked="WPFOkApplyModifyGetOnOffCancel_OkClicked" OnOffClicked="WPFOkApplyModifyGetOnOffCancel_OnOffClicked" ModifyClicked="WPFOkApplyModifyGetOnOffCancel_ModifyClicked"/>

    </Grid>
</tsd:PluginWindowBase>
